-  request:
      method: GET
      url: /hello-world

   response:
      status: 200
      headers:
         content-type: application/json
      body: Hello World!

-  request:
      method: POST
      url: /status

   response:
      status: 442
      headers:
         Content-Type: application/octet-stream
         Content-Length: 11
         Connection: keep-alive
         Avast-Kluzo-TraceId: krzumc3odk
      body: Key expired
